version: '3'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    build: .
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: "1"
      KAFKA_HOST: localhost
      KAFKA_PORT: 9092
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "turbine-raw:1:1,turbine-agg:1:1"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - zookeeper
  mydb:
      image: postgres:12.1
      volumes:
        - ./postgres-data:/var/lib/postgresql/data
      environment:
        - POSTGRES_USER=meetup
        # Provide the password via an environment variable. If the variable is unset or empty, use a default password
        - POSTGRES_PASSWORD=secret
        - POSTGRES_DB=turbines
      ports:
      - 5432:5432
